# Generated by Django 5.0.1 on 2024-01-04 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0002_alter_position_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasktype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={"ordering": ["position"]},
        ),
    ]
