# Generated by Django 5.0.1 on 2024-01-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0003_alter_tasktype_options_alter_worker_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="task_type",
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.ManyToManyField(blank=True, to="task_manager.tasktype"),
        ),
    ]
