# Generated by Django 5.0.1 on 2024-01-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0004_remove_task_task_type_task_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.ManyToManyField(
                related_name="tasks", to="task_manager.tasktype"
            ),
        ),
    ]
