# Generated by Django 5.0.1 on 2024-01-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0006_alter_task_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to="task_manager.project"
            ),
        ),
    ]
