# Generated by Django 4.1.12 on 2024-01-04 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0007_alter_team_projects"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="worker",
            managers=[],
        ),
    ]
