# Generated by Django 4.1.12 on 2024-01-04 23:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0009_alter_worker_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="worker",
            managers=[],
        ),
    ]
