# Generated by Django 4.1.12 on 2024-01-04 23:48

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0010_alter_worker_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="worker",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
