# Generated by Django 5.0.1 on 2024-01-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0011_alter_worker_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
