# Generated by Django 5.0.1 on 2024-01-09 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "task_manager",
            "0016_remove_team_workers_project_description_worker_team_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="task_manager.project",
            ),
        ),
    ]
