# Generated by Django 5.0.1 on 2024-01-10 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0018_alter_task_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="team",
        ),
        migrations.AddField(
            model_name="team",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
