# Generated by Django 5.0.1 on 2024-01-10 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0019_remove_worker_team_team_worker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="worker",
        ),
        migrations.AddField(
            model_name="team",
            name="worker",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
