# Generated by Django 5.0.1 on 2024-01-10 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0021_rename_worker_team_workers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasktype",
            name="task",
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="task_manager.tasktype",
            ),
        ),
    ]
