# Generated by Django 5.0.1 on 2024-01-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0022_remove_tasktype_task_task_task_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="task_type",
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.ManyToManyField(
                null=True, related_name="tasks", to="task_manager.tasktype"
            ),
        ),
    ]
