# Generated by Django 5.0.1 on 2024-01-10 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0023_remove_task_task_type_task_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.ManyToManyField(
                related_name="tasks", to="task_manager.tasktype"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="workers",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
