# Generated by Django 5.0.1 on 2024-01-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0024_alter_task_task_type_alter_team_workers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="is_complete",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
