# Generated by Django 4.2.9 on 2024-01-11 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0026_alter_team_workers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="workers",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
