# Generated by Django 4.2.9 on 2024-01-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0027_alter_team_workers"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
