# Generated by Django 4.2.9 on 2024-01-15 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0028_project_budget"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name", "is_complete"]},
        ),
    ]
