# Generated by Django 4.2.9 on 2024-01-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0030_alter_project_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name", "is_complete"]},
        ),
        migrations.AlterField(
            model_name="worker",
            name="phone_number",
            field=models.CharField(
                help_text="For example '+380951911919'. Without quotes", max_length=13
            ),
        ),
    ]
