# Generated by Django 4.2.9 on 2024-01-15 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0031_alter_project_options_alter_worker_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name"]},
        ),
    ]
