# Generated by Django 4.2.9 on 2024-01-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0033_worker_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.DateTimeField(blank=True, default="-", null=True),
        ),
    ]
